FROM ubuntu:14.04

# Python and sudo is required to run Ansible modules
RUN apt-get update && apt-get install -y python sudo

# Init hack, see https://hub.docker.com/_/ubuntu-upstart/
ADD init-fake.conf /etc/init/fake-container-events.conf
RUN rm /usr/sbin/policy-rc.d; \
	rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl

CMD ["/sbin/init"]
